// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {scanner} from '../models';
import {db} from '../models';
import {resolver} from '../models';
import {instance} from '../models';
import {main} from '../models';
import {embeddings} from '../models';

export function BrowseForFolder():Promise<string>;

export function GetAbsoluteConfigPath(arg1:string):Promise<string>;

export function GetAllConfigFiles():Promise<Array<scanner.ConfigFile>>;

export function GetConfigsForMod(arg1:string):Promise<Array<db.ConfigMapping>>;

export function GetDependencyGraph():Promise<resolver.Graph>;

export function GetInstanceName():Promise<string>;

export function GetInstances():Promise<Array<instance.Instance>>;

export function GetInstancesForSettings(arg1:db.Settings):Promise<Array<instance.Instance>>;

export function GetMissingDependencies():Promise<Array<resolver.MissingDep>>;

export function GetModDetail(arg1:string):Promise<main.ModDetail>;

export function GetMods():Promise<Array<db.Mod>>;

export function GetReverseDependencies(arg1:string):Promise<Array<main.ReverseDep>>;

export function GetSettings():Promise<db.Settings>;

export function GetUnusedLibraries():Promise<Array<string>>;

export function ReadConfigFile(arg1:string):Promise<string>;

export function RemoveConfigOverride(arg1:string,arg2:string):Promise<void>;

export function ResetDatabase():Promise<void>;

export function SaveConfigFile(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:db.Settings):Promise<void>;

export function ScanNow():Promise<void>;

export function SearchMods(arg1:string):Promise<Array<embeddings.SearchResult>>;

export function SetConfigOverride(arg1:string,arg2:string):Promise<void>;
