// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseForFolder() {
  return window['go']['main']['App']['BrowseForFolder']();
}

export function GetAbsoluteConfigPath(arg1) {
  return window['go']['main']['App']['GetAbsoluteConfigPath'](arg1);
}

export function GetAllConfigFiles() {
  return window['go']['main']['App']['GetAllConfigFiles']();
}

export function GetConfigsForMod(arg1) {
  return window['go']['main']['App']['GetConfigsForMod'](arg1);
}

export function GetDependencyGraph() {
  return window['go']['main']['App']['GetDependencyGraph']();
}

export function GetInstanceName() {
  return window['go']['main']['App']['GetInstanceName']();
}

export function GetInstances() {
  return window['go']['main']['App']['GetInstances']();
}

export function GetInstancesForSettings(arg1) {
  return window['go']['main']['App']['GetInstancesForSettings'](arg1);
}

export function GetMissingDependencies() {
  return window['go']['main']['App']['GetMissingDependencies']();
}

export function GetModDetail(arg1) {
  return window['go']['main']['App']['GetModDetail'](arg1);
}

export function GetMods() {
  return window['go']['main']['App']['GetMods']();
}

export function GetReverseDependencies(arg1) {
  return window['go']['main']['App']['GetReverseDependencies'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetUnusedLibraries() {
  return window['go']['main']['App']['GetUnusedLibraries']();
}

export function ReadConfigFile(arg1) {
  return window['go']['main']['App']['ReadConfigFile'](arg1);
}

export function RemoveConfigOverride(arg1, arg2) {
  return window['go']['main']['App']['RemoveConfigOverride'](arg1, arg2);
}

export function ResetDatabase() {
  return window['go']['main']['App']['ResetDatabase']();
}

export function SaveConfigFile(arg1, arg2) {
  return window['go']['main']['App']['SaveConfigFile'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanNow() {
  return window['go']['main']['App']['ScanNow']();
}

export function SearchMods(arg1) {
  return window['go']['main']['App']['SearchMods'](arg1);
}

export function SetConfigOverride(arg1, arg2) {
  return window['go']['main']['App']['SetConfigOverride'](arg1, arg2);
}

export function SetLibraryOverride(arg1, arg2) {
  return window['go']['main']['App']['SetLibraryOverride'](arg1, arg2);
}
